version: "3.9"
services:
  app:
    image: php:8.4-fpm-alpine
    container_name: laravel_app
    working_dir: /var/www/html
    env_file: .env
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    command: php artisan serve --host=0.0.0.0 --port=9000